language: ruby
rvm:
  - 2.2.3
cache: bundler
before_install:
  - cd super_goal
bundler_args: --without development production
before_script:
  - rake db:migrate RAILS_ENV=test
  - rake db:test:prepare
script:
  - bundle exec rspec spec
