language: ruby
rvm:
  - 2.2.3
cache: bundler
before_script:
  - cd super_goal
  - bundle install --without development staging production
  - rake db:migrate
  - rake db:test:prepare
script:
  - bundle exec rspec spec
